### ISSUE TITLE
No position encoding code found

### ISSUE THREAD

**Issue by Lunarli** [ruibing-jin/PE-Net#1]
I can not find the  position encoding code from the sharing code.
The model only consists of cnn layers and fc layers.
Can you tell me where to find this?  Very Thanks!

**Comment by ruibing-jin** [comment]
The position encoding code is included in ./dataset/data_loader.py, line 224-225 and line 365-366. You can refer to the exps/pe_net_fd004.yaml for using it.

**Comment by ruibing-jin** [comment]
The position encoding code is included in ./dataset/data_loader.py, line 224-225 and line 365-366. You can refer to the exps/pe_net_fd004.yaml for using it.
